framework:
    messenger:
        transports:
            async-high:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    exchange:
                        name: messages
                        type: direct
                    auto_setup: true
                    queues:
                        async-high:
                            binding_keys: [async-high]
            async-medium:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    exchange:
                        name: messages
                        type: direct
                    auto_setup: true
                    queues:
                        async-medium:
                            binding_keys: [async-medium]
            async-low:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    exchange:
                        name: messages
                        type: direct
                    auto_setup: true
                    queues:
                        async-low:
                            binding_keys: [async-low]
            sync: 'sync://'

        routing:
            App\Application\Command\CreateOrUpdateFacebookAccount: sync
            App\Application\Command\CreateOrUpdateTwitterAccount: sync
            App\Application\Command\CreateOrUpdateLinkedinAccount: sync
            App\Application\Command\CreateOrUpdateYoutubeAccount: sync
            App\Application\Command\CreateOrganization: sync
            App\Application\Command\DeletePost: sync
            
            App\Application\Command\RemoveSocialAccount: async-low
            App\Application\Command\ExpireSocialAccount: async-high
            App\Application\Command\PublishCluster: async-medium
            App\Application\Command\PublishPost: async-medium
            App\Application\Command\UpdateClusterStatus: async-medium
            App\Application\Command\DeleteCluster: async-low
            App\Application\Command\RemoveUnusedMediaPost: async-low
            App\Application\Command\UploadToS3MediaPost: async-high