framework:
    messenger:
        transports:
            async:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    exchange:
                        name: messages
                        type: direct
                    auto_setup: true
                    queues:
                        async:
                            binding_keys: [async]
            sync: 'sync://'
        routing:
            App\Application\Command\CreateOrUpdateFacebookAccount: sync
            App\Application\Command\CreateOrUpdateTwitterAccount: sync
            App\Application\Command\CreateOrganization: sync
            App\Application\Command\RemoveSocialAccount: async