parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $apiUrl: '%env(resolve:API_URL)%'
            string $frontUrl: '%env(resolve:FRONT_URL)%'
            string $facebookClientId: '%env(resolve:FACEBOOK_CLIENT_ID)%'
            string $facebookClientSecret: '%env(resolve:FACEBOOK_CLIENT_SECRET)%'
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    app.event.authentication_success_listener:
        class: App\EventListener\AuthenticationSuccessListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }